const quizData = [
    {
        question: "Q : 01--> What is the meaning of CSS?",
        a: "Creative Software Server",
        b: "Clear Software Society",
        c: "Cascading Style Sheets",
        d: "Comilla Software School",
        correct: "c",
    },
    {
        question: "Q : 02--> What is the capital of Uganda?",
        a: "Washington",
        b: "Kampala",
        c: "Islamabad",
        d: "Mymensingh",
        correct: "b",
    },
    {
        question: "Q : 03--> Diligent means?",
        a: "inactive",
        b: "foolish",
        c: "dedicated",
        d: "bad",
        correct: "c",
    },
    {
        question: "Q : 04--> Who is the prime minister of canada?",
        a: "Justin Treadue",
        b: "Mohammad Salman",
        c: "Sheikh Hasina",
        d: "Norendra Modi",
        correct: "a",
    },
    {
        question: "Q : 05--> Choose the correct HTML element for the smallest heading:",
        a: "<h1>",
        b: "<h6>",
        c: "<heading>",
        d: "<head>",
        correct: "b",
    },
    {
        question: "Q : 06--> What is the correct HTML element for inserting an image?",
        a: "<image>",
        b: "<i>",
        c: "<photo>",
        d: "<img>",
        correct: "d",
    },
    {
        question: "Q : 07--> Who is the first Bangladeshi to achieve a noble prize?",
        a: "Khaleda Zia",
        b: "Mohammad Salman",
        c: "Mohammad Younus",
        d: "Mohammad Kabir",
        correct: "c",
    },
    {
        question: "Q : 08--> Leonel Messi is currently playing in which team?",
        a: "Brazil",
        b: "Barcelona",
        c: "Paris Saint German",
        d: "Bashundhara Kings Arena",
        correct: "c",
    },
];

