const quizData = [
    {
        question: "Q : 01--> What is the rank of DIU among all private Universities of Bangladesh in QS Asia Rankings-2022?",
        a: "1st",
        b: "2nd",
        c: "3rd",
        d: "4th",
        correct: "c",
    },
    
    {
        question: "Q : 02--> What is the capital of Bangladesh?",
        a: "Dhaka",
        b: "Chittagong",
        c: "Rajshahi",
        d: "Mymensingh",
        correct: "a",
    },
   
{
        question: "Q : 03--> Where is the permanent campus of Daffodil International University?",
        a: "Mirpur, Dhaka",
        b: "Cumilla",
        c: "Rangpur",
        d: "Ashulia, Savar",
        correct: "d",
    },

      {
        question: "Q : 04--> Who is making the Web standards?",
        a: "Mozilla",
        b: "Goofle",
        c: "Microsoft",
        d: "WWW Consortium",
        correct: "d",
          
    },
{
        question: "Q : 05--> Choose the correct HTML element for the largest heading:",
        a: "<h1>",
        b: "<h6>",
        c: "<heading>",
        d: "<head>",
        correct: "a",
    },
    {
        question: "Q : 06--> What is the correct HTML element for inserting a line break?",
        a: "<lb>",
        b: "<break>",
        c: "<br>",
        d: "< >",
        correct: "c",
    },
     {
        question: "Q : 07--> What is the correct HTML element to define important text?",
        a: "<b>",
        b: "<important>",
        c: "<strong>",
        d: "<i>",
        correct: "c",
    },
    {
        question: "Q : 08--> Which character is used to indicate an end tag?",
        a: "<<>",
        b: "</>",
        c: "<*>",
        d: "<^>",
        correct: "b",
    },
   {
        question: "Q : 08--> Which character is used to indicate an end tag?",
        a: "<<>",
        b: "</>",
        c: "<*>",
        d: "<^>",
        correct: "b",
    }, 
